# config/dwa_local_planner_params.yaml
DWAPlannerROS:
  # Kinematik (Tuning)
  max_vel_x: 0.50
  min_vel_x: -0.10
  max_vel_theta: 1.0
  acc_lim_x: 0.8
  acc_lim_theta: 1.0

  # Simulasi (Tuning)
  sim_time: 1.5 # Jendela simulasi pendek
  vx_samples: 20
  vtheta_samples: 40

  # Scoring
  path_distance_bias: 32.0 # Agresif mengikuti jalur global
  goal_distance_bias: 24.0
  occdist_scale: 0.02 # Sensitivitas terhadap rintangan