# local_costmap_params.yaml
local_costmap:
   # Frame referensi
   global_frame: odom
   robot_base_frame: base_link
   update_frequency: 5.0 # Update map 5x per detik (reaktif)
   publish_frequency: 2.0
   static_map: false # Tidak menggunakan peta statis
   rolling_window: true # Menggulir peta di sekitar robot
   width: 4.0 # Lebar jendela lokal (m)
   height: 4.0 # Tinggi jendela lokal (m)
   resolution: 0.05